#!/bin/bash
# Setup the docker environment with respective ssh keys and spin up containers
# Assumes docker and docker-compose are already installed in the host system

# Generate SSH Keys
sh $(dirname $0)/generate_keys

# Run containers
docker-compose -f $(dirname $0)/compose.yaml up -d --build